[font]
normal.family = 'Inconsolata Nerd Font'
size = 16

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 0.98

# Colors (Nord)

# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

[colors.cursor]
text   = '#2E3440'
cursor = '#D8DEE9'

[colors.vi_mode_cursor]
text   = '#2E3440'
cursor = '#88C0D0'

[colors.selection]
text       = 'CellForeground'
background = '#434C5E'

[colors.search.matches]
foreground = '#2E3440'
background = '#88C0D0'

[colors.search.focused_match]
foreground = '#2E3440'
background = '#8FBCBB'

[colors.hints.start]
foreground = '#2E3440'
background = '#EBCB8B'

[colors.hints.end]
foreground = '#2E3440'
background = '#4C566A'

[colors.footer_bar]
foreground = '#D8DEE9'
background = '#3B4252'

# Normal colors
[colors.normal]
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'
